# Generated by Django 5.0.6 on 2024-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.URLField(default='', verbose_name='Video Link'),
            preserve_default=False,
        ),
    ]
