# Generated by Django 5.0.6 on 2024-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_course_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.CharField(max_length=11, verbose_name='Video Link'),
        ),
    ]
