# Generated by Django 5.0.6 on 2024-07-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_alter_course_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
