# Generated by Django 5.0.6 on 2024-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0007_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300, verbose_name='job_title')),
                ('link', models.CharField(max_length=300, verbose_name='link')),
                ('source', models.CharField(max_length=300, verbose_name='source')),
                ('salary_from', models.CharField(max_length=300, verbose_name='salary_from')),
                ('salary_to', models.CharField(max_length=300, verbose_name='salary_to')),
                ('salary_currency', models.CharField(max_length=300, verbose_name='salary_currency')),
                ('salary_periodicity', models.CharField(max_length=300, verbose_name='salary_periodicity')),
                ('salary_period', models.CharField(max_length=300, verbose_name='salary_period')),
                ('based_on', models.CharField(max_length=300, verbose_name='based_on')),
            ],
        ),
    ]
